// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package controller

import (
	"go.uber.org/zap"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/win5do/etcd-operator/api/v1"
	"github.com/win5do/etcd-operator/pkg/conf"
	"github.com/win5do/etcd-operator/pkg/k8s"
)

// Injectors from wire.go:

func Inject(cli client.Client, scheme *runtime.Scheme, cr *v1.Etcd, log *zap.SugaredLogger, cfg conf.Config) *controller {
	kcli := k8s.NewKcli(cli, scheme, log, cr)
	resourceBuilder := NewResourceBuilder(cr)
	controllerStatusManager := &statusManager{
		kcli: kcli,
	}
	controllerController := &controller{
		reqLog:        log,
		cr:            cr,
		cfg:           cfg,
		Kcli:          kcli,
		Builder:       resourceBuilder,
		StatusManager: controllerStatusManager,
	}
	return controllerController
}
